// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA3ufmwIMlzlDoCdK_rUYN5IoIbv_2Ors',
    appId: '1:165908523998:web:cde0b9e921f92d2f56cb4f',
    messagingSenderId: '165908523998',
    projectId: 'lb4students',
    authDomain: 'lb4students.firebaseapp.com',
    databaseURL: 'https://lb4students-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lb4students.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJFs_lf9MJGkqG2ceU-qLLPaOg00M0L3g',
    appId: '1:165908523998:android:1ecbf5ec6c3b692656cb4f',
    messagingSenderId: '165908523998',
    projectId: 'lb4students',
    databaseURL: 'https://lb4students-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lb4students.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgRHX-k1_G6YBvFLokqH1B0cqCCJTNBPk',
    appId: '1:165908523998:ios:8200b495829649ed56cb4f',
    messagingSenderId: '165908523998',
    projectId: 'lb4students',
    databaseURL: 'https://lb4students-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lb4students.firebasestorage.app',
    iosBundleId: 'com.example.kiuki219Fenchenko',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgRHX-k1_G6YBvFLokqH1B0cqCCJTNBPk',
    appId: '1:165908523998:ios:8200b495829649ed56cb4f',
    messagingSenderId: '165908523998',
    projectId: 'lb4students',
    databaseURL: 'https://lb4students-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lb4students.firebasestorage.app',
    iosBundleId: 'com.example.kiuki219Fenchenko',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA3ufmwIMlzlDoCdK_rUYN5IoIbv_2Ors',
    appId: '1:165908523998:web:803cd3a8834ec5aa56cb4f',
    messagingSenderId: '165908523998',
    projectId: 'lb4students',
    authDomain: 'lb4students.firebaseapp.com',
    databaseURL: 'https://lb4students-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lb4students.firebasestorage.app',
  );

}